CREATE DATABASE BIBLIOTECA;

USE BIBLIOTECA;

CREATE TABLE LIVROS (
ID int,Primary key(ID),
TITULO VARCHAR(45),
AUTOR VARCHAR(45),
ANO_LANCAMENTO DATE,
EDITORA VARCHAR(45)
);

INSERT INTO LIVROS VALUES (1,'UMA BREVE HISTÓRIA DO TEMPO','STEPHEN HAWKING','1988-01-13','Intrínseca'),
						  (2,'PAI RICO PAI POBRE','ROBERT T.KYOSAKY','2018-09-05','ALTAS BOOKS'),
                          (3,'UMA BREVE HISTORIA DA HUMANIDADE','YUVAL NOAH HARARI','2015-01-01','L&PM');
					
			
select * from livros;